#!/usr/bin/env bash

#PBS -l select=1:ncpus=2:mem=4gb
#PBS -l walltime=12:00:00
#PBS -j oe

##PBS -M your.email.here@unsw.edu.au #(uncomment to receive email notification)
##PBS -m ae

cd $PBS_O_WORKDIR

module add openjdk/11.0.2 singularity/3.6.4
unset JAVA_TOOL_OPTIONS

curl -s https://get.nextflow.io | bash

export NXF_OPTS='-Xms1g -Xmx4g'
./nextflow run nf-core/rnaseq -params-file nf-params.json --outdir results --igenomes_base '/data/bio/igenomes/references' -resume